name: Compare Bench
# It runs default OSes for each PR, push event or a new tag,
# checks basic builds with various compilers and executes all sets of tests.

on:
  workflow_dispatch:
    inputs:
      BASELINE_REF:
        description: 'BASELINE_REF'
        required: true
        default: 'master'
        type: string
      COMPARE_REF:
        description: 'COMPARE_REF'
        required: false
        default: 'HEAD'
        type: string
      PR:
        description: 'PR'
        required: false
        default: ''
        type: string
      COMPARE_REPO_ADDR:
        description: 'COMPARE_REPO_ADDR'
        required: true
        default: 'https://github.com/pmem/pmemstream'
        type: string
      BASELINE_REPO_ADDR:
        description: 'BASELINE_REPO_ADDR'
        required: true
        default: 'https://github.com/pmem/pmemstream'
        type: string
      QUIET:
        description: 'QUIET'
        required: true
        default: true
        type: boolean
  pull_request:
  release:

jobs:
  linux:
    name: Linux-Self_Hosted
 #   if: github.repository == 'pmem/pmemstream'

    runs-on: self-hosted
    env:
      PMEMSTREAM_TEST_DIR: /mnt/pmem0/${{ github.job }}
      CHECK_CPP_STYLE: OFF

    steps:
        - name: Clone the git repo
          uses: actions/checkout@v2

        - name: Check github event
          if: contains(fromJson('["push", "pull_request"]'), github.event_name)
          env:
            PR_NUMBER: ${{ github.event.number }}
          run: echo "PR_NUMBER ${{ github.event.number }}"

        - name: Run run-compare-bench script
          run: |
            set -x
            VERBOSE_PARAM=''
            if ${{ inputs.QUIET }}; then
              VERBOSE_PARAM="-q"
            fi

            PR_PARAM=''
            if [ ! ${{ inputs.PR }} == '' ]; then
              PR_PARAM="--pr=${{ inputs.PR }}"
            fi

            COMPARE_REF_PARAM=''
            if [ ! ${{ inputs.COMPARE_REF }} == '' ]; then
              COMPARE_REF_PARAM="--ref=${{ inputs.COMPARE_REF }}"
            fi

            ./utils/docker/run-compare-bench.sh -t $VERBOSE_PARAM $PR_PARAM $COMPARE_REF_PARAM --baseline_repo=${{ inputs.BASELINE_REPO_ADDR }} --baseline_ref=${{ inputs.BASELINE_REF }} --compare_repo=${{ inputs.BASELINE_REPO_ADDR }}
          shell: bash
